Models/Yemek.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace YemekSitesi.Models
{
    public class Yemek
    {
        public int ID { get; set; }
        [Required]
        public string Isim { get; set;}
        public string Mensei { get; set; }
        public int Zorluk { get; set; }
        public int Kisi { get; set; }
        public int PisirmeSuresi { get; set; }
        public String Tur { get; set; }
        [Required]
        public string Hazirlanis { get; set; }

        public virtual ICollection<Icerik> Icerikler { get; set; }
    }

    public static class YemekTuru
    {
        public static string CORBALAR = "ÇORBALAR";
        public static string TATLILAR = "TATLILAR";
        public static string ET_YEMEKLERI = "ET-BALIK-TAVUK";
        public static string KAHVALTILIKLAR = "KAHVALTILIKLAR";
        public static string SEBZELI_YEMEKLER = "SEBZELİ YEMEKLER";
        public static string HAMUR_ISLERI = "HAMUR İŞLERİ";
        public static string PILAVLAR = "PİLAVLAR";
    }
}

Controllers/YemekController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using YemekSitesi.Models;
using YemekSitesi.DAL;
using PagedList;

namespace YemekSitesi.Controllers
{
    public class YemekController : Controller
    {
        private YemekContext db = new YemekContext();

        // GET: /Yemek/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PisirmeSortParm = sortOrder == "Pisirme" ? "pisirme_desc" : "Pisirme";
            var yemekler = from s in db.Yemekler
                           select s;

            if(searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if(!String.IsNullOrEmpty(searchString))
            {
                yemekler = yemekler.Where(y => y.Isim.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    yemekler = yemekler.OrderByDescending(s => s.Isim);
                    break;
                case "Pisirme":
                    yemekler = yemekler.OrderBy(s => s.PisirmeSuresi);
                    break;
                case "pisirme_desc":
                    yemekler = yemekler.OrderByDescending(s => s.PisirmeSuresi);
                    break;
                default:
                    yemekler = yemekler.OrderBy(s => s.Isim);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(yemekler.ToPagedList(pageNumber,pageSize));
        }

        // GET: /Yemek/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yemek yemek = db.Yemekler.Find(id);
            if (yemek == null)
            {
                return HttpNotFound();
            }
            return View(yemek);
        }

        // GET: /Yemek/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Yemek/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Isim,Mensei,Zorluk,Kisi,PisirmeSuresi,Tur,Hazirlanis")] Yemek yemek)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Yemekler.Add(yemek);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException e)
            {
                ModelState.AddModelError("", "Unable to save changes. Error message:" + e.Message);
            }
            return View(yemek);
        }

        // GET: /Yemek/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yemek yemek = db.Yemekler.Find(id);
            if (yemek == null)
            {
                return HttpNotFound();
            }
            return View(yemek);
        }

        // POST: /Yemek/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Isim,Mensei,Zorluk,Kisi,PisirmeSuresi,Hazirlanis")] Yemek yemek)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(yemek).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException e)
            {
                ModelState.AddModelError("", "Unable to save changes. Error message:" + e.Message);
            }
            return View(yemek);
        }

        // GET: /Yemek/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError=false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            Yemek yemek = db.Yemekler.Find(id);
            if (yemek == null)
            {
                return HttpNotFound();
            }
            return View(yemek);
        }

        // POST: /Yemek/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                Yemek yemek = db.Yemekler.Find(id);
                db.Yemekler.Remove(yemek);
                db.SaveChanges();
            }
            catch (DataException )
            {
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Yemek/Create.cshtml
@model YemekSitesi.Models.Yemek

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Yemek</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Isim, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Isim)
                @Html.ValidationMessageFor(model => model.Isim)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mensei, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mensei)
                @Html.ValidationMessageFor(model => model.Mensei)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zorluk, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zorluk)
                @Html.ValidationMessageFor(model => model.Zorluk)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kisi, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kisi)
                @Html.ValidationMessageFor(model => model.Kisi)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PisirmeSuresi, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PisirmeSuresi)
                @Html.ValidationMessageFor(model => model.PisirmeSuresi)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tur, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Tur)
                @Html.ValidationMessageFor(model => model.Tur)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hazirlanis, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Hazirlanis,5,23,null)
                @Html.ValidationMessageFor(model => model.Hazirlanis)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Yemek/Delete.cshtml
@model YemekSitesi.Models.Yemek

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<p class="error">@ViewBag.ErrorMessage</p>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Yemek</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Isim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Isim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mensei)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mensei)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zorluk)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zorluk)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kisi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PisirmeSuresi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PisirmeSuresi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hazirlanis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hazirlanis)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Yemek/Details.cshtml
@model YemekSitesi.Models.Yemek

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Yemek</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Isim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Isim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mensei)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mensei)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zorluk)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zorluk)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kisi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PisirmeSuresi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PisirmeSuresi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hazirlanis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hazirlanis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Icerikler)
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Malzeme İsmi</th>
                    <th>Miktarı</th>
                </tr>
                @foreach (var item in Model.Icerikler)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Malzeme.Isim)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MiktarAdeti)
                            @Html.DisplayFor(modelItem => item.MiktarTuru)
                        </td>
                    </tr>
                }
            </table>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Yemek/Edit.cshtml
@model YemekSitesi.Models.Yemek

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Yemek</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Isim, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Isim)
                @Html.ValidationMessageFor(model => model.Isim)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mensei, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mensei)
                @Html.ValidationMessageFor(model => model.Mensei)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zorluk, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zorluk)
                @Html.ValidationMessageFor(model => model.Zorluk)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kisi, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kisi)
                @Html.ValidationMessageFor(model => model.Kisi)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PisirmeSuresi, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PisirmeSuresi)
                @Html.ValidationMessageFor(model => model.PisirmeSuresi)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hazirlanis, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hazirlanis)
                @Html.ValidationMessageFor(model => model.Hazirlanis)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Yemek/Index.cshtml
@model PagedList.IPagedList<YemekSitesi.Models.Yemek>
@using PagedList;
@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Yemekler";
}

<h2>Yemekler</h2>

<p>
    @Html.ActionLink("Yemek Ekle", "Create")
</p>

@using (Html.BeginForm("Index","Yemek",FormMethod.Get))
{
    <p>
        İsme göre Ara: @Html.TextBox("SearchString",ViewBag.CurrentFilter as string)
        <input type="submit" value="Ara" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("İsim", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Menşei
        </th>
        <th>
            Zorluk Seviyesi
        </th>
        <th>
            Kişi Sayısı
        </th>
        <th>
            @Html.ActionLink("Pişirme Süresi", "Index", new { sortOrder = ViewBag.PisirmeSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Yemek Türü
        </th>
        <th>
            Hazırlanışı
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Isim)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mensei)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Zorluk)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kisi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PisirmeSuresi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tur)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hazirlanis)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",new{ page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))